print("What is you username?")
User = input()
print("What is your special ability?")
Special = input()
print("How strong is your punch? (0/100)")
Strength = input()
print("Do you want a weapon? True/False")
WantsWeapon = input()
if WantsWeapon == "True":
    print("Pick any weapon you want")
    Weapon = input()
    print("How strong is that", Weapon,"? (0/100)")
    WStrength = input()
elif WantsWeapon == "true":
    print("Pick any weapon you want")
    Weapon = input()
    print("How strong is that", Weapon,"? (0/100)")
    WStrength = input()
print("How fast are you? (any number)")
Speed = input()
print("What is your play style?")
Strat = input()
print("What type of armor do you have?")
Armour = input()
print("What is the durability of your armor?")
Dur = input()
print("Username:", User)
print("Special ability:", Special)
print("Strength:", Strength)
print("Wants a Weapon:", WantsWeapon)
if WantsWeapon == "True":
    print("Weapon:", Weapon)
    print("Weapon strength:", WStrength)
elif WantsWeapon == "true":
    print("Weapon:", Weapon)
    print("Weapon strength:", WStrength)
print("Speed:", Speed)
print("Play style:", Strat)
print("Armour:", Armour)
print("Armour durability:", Dur)
input()